version: "3.9"

volumes:
  db-volume:

services:
  pg:
    build: ./postgresql
    container_name: pg
    restart: always
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
  server:
    depends_on:
      - pg
    container_name: server
    build: .
    volumes:
      - ./logs:/app/logs
    ports:
      - "8080:8080"